version: '3.8'

services:
  backend:
    build:
      context: ./server
    ports:
      - "3001:3001"
    volumes:
      - ./server:/app
    env_file:
      - ./server/.env
    depends_on:
      - db

  frontend:
    build:
      context: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - backend

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: techrino_user
      POSTGRES_PASSWORD: techrino_pass
      POSTGRES_DB: techrino_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: